// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.3.2.0
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace UserGro.Tests.Behavior
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Message")]
    public partial class MessageFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "UserSendMessage.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Message", "In order to communicated with other users\r\nAs a site user\r\nI want to be able to s" +
                    "end messages", ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("User Send Message")]
        public virtual void UserSendMessage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("User Send Message", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line 8
testRunner.Given("I am a user logged into the system");
#line 9
testRunner.When("I send a message to another user");
#line 10
testRunner.And("I am not their friend");
#line 11
testRunner.And("they allow messages to be sent to them from nonfriends");
#line 12
testRunner.Then("my message is in their inbox");
#line 14
testRunner.Given("I am a user logged into the system");
#line 15
testRunner.When("I send a message to another user");
#line 16
testRunner.And("I am not their friend");
#line 17
testRunner.And("they do NOT allow messages to be sent to them from nonfriends");
#line 18
testRunner.Then("my message is NOT in their inbox");
#line 20
testRunner.Given("I am a user logged into the system");
#line 21
testRunner.When("I send a message to another user");
#line 22
testRunner.And("the user is my friend");
#line 23
testRunner.Then("my message is in their inbox");
#line 25
testRunner.Given("I am a user logged into the system");
#line 26
testRunner.When("I send a message to a non-existant user");
#line 27
testRunner.Then("I receive an exception");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
