// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.3.2.0
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace UserGro.Tests.Behavior
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("In order to manage nearby groups / events")]
    public partial class InOrderToManageNearbyGroupsEventsFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "User.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "In order to manage nearby groups / events", "As a programmer\r\nI want to see everything available", ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Privacy respected")]
        public virtual void PrivacyRespected()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Privacy respected", ((string[])(null)));
#line 5
this.ScenarioSetup(scenarioInfo);
#line 6
testRunner.Given("I am a user that allows friends only to view page");
#line 7
testRunner.When("a nonfriend requests my information");
#line 8
testRunner.Then("only basic information is returned");
#line 10
testRunner.Given("I am a user that allows friends only to view page");
#line 11
testRunner.When("a friend requests my information");
#line 12
testRunner.Then("my full profile information is displayed");
#line 14
testRunner.Given("I am a user that requires authentication to be my friend");
#line 15
testRunner.When("a user requests to be my friend");
#line 16
testRunner.Then("they are added to awaiting approval");
#line 17
testRunner.And("not added to friends");
#line 19
testRunner.Given("I am a user that requires authentication to be my friend");
#line 20
testRunner.When("a friend requests to be my friend");
#line 21
testRunner.Then("they are not added to my friends list twice");
#line 23
testRunner.Given("I am a user that does NOT require authentication to be my friend");
#line 24
testRunner.When("a user requests to be my friend");
#line 25
testRunner.Then("they are added to my friends list");
#line 26
testRunner.And("I am added to their friend list");
#line 28
testRunner.Given("I am a user that does NOT require authentication to be my friend");
#line 29
testRunner.When("a friend requests to be my friend");
#line 30
testRunner.Then("they are not added to my friends list twice");
#line 32
testRunner.Given("I am a user that has a friend in my awaiting confirmation list");
#line 33
testRunner.When("I approve the friend");
#line 34
testRunner.Then("the friend is added to my friends list");
#line 35
testRunner.And("is no longer in my awaiting confirmation list");
#line 37
testRunner.Given("I am a user that has a friend in my awaiting confirmation list");
#line 38
testRunner.And("the user is somehow in my friend list");
#line 39
testRunner.When("I approve the friend");
#line 40
testRunner.Then("the friend is still only in my friends list once");
#line 41
testRunner.And("is no longer in my awaiting confirmation list");
#line 43
testRunner.Given("I am a user that is not part of the local .NET group");
#line 44
testRunner.When("I attempt to join the group");
#line 45
testRunner.And("the group does not require approval");
#line 46
testRunner.Then("it is added to my groups");
#line 48
testRunner.Given("I am a user that is not part of the local .NET group");
#line 49
testRunner.When("the group DOES require approval");
#line 50
testRunner.And("I attempt to join the group");
#line 51
testRunner.Then("I am added to the groups Awaiting approval");
#line 53
testRunner.Given("I am a user that wants to attend a local day of .NET");
#line 54
testRunner.When("I attempt to register for the event");
#line 55
testRunner.And("there is still room to join the event");
#line 56
testRunner.Then("I am added to the event\'s attendee\'s");
#line 57
testRunner.And("the event is added to my EventsAttending");
#line 59
testRunner.Given("I am a user that wants to start an event");
#line 60
testRunner.When("I create an event");
#line 61
testRunner.Then("it gets added to my events admin");
#line 62
testRunner.And("it gets added to my events attending");
#line 64
testRunner.Given("I am a user that is an event admin");
#line 65
testRunner.When("I remove an attendee");
#line 66
testRunner.Then("they are no longer in the list of those coming");
#line 68
testRunner.Given("I am a user that is an event admin");
#line 69
testRunner.When("I promote another user to admin the event");
#line 70
testRunner.Then("they are promoted to admin");
#line 72
testRunner.Given("I am a user logged into the system");
#line 73
testRunner.When("I send a message to another user");
#line 74
testRunner.And("I am not their friend");
#line 75
testRunner.And("they allow messages to be sent to them from nonfriends");
#line 76
testRunner.Then("my message is in their inbox");
#line 78
testRunner.Given("I am a user logged into the system");
#line 79
testRunner.When("I send a message to another user");
#line 80
testRunner.And("I am not their friend");
#line 81
testRunner.And("they do NOT allow messages to be sent to them from nonfriends");
#line 82
testRunner.Then("my message is NOT in their inbox");
#line 84
testRunner.Given("I am a user logged into the system");
#line 85
testRunner.When("I send a message to another user");
#line 86
testRunner.And("the user is my friend");
#line 87
testRunner.Then("my message is in their inbox");
#line 89
testRunner.Given("I am a user logged into the system");
#line 90
testRunner.When("I send a message to a non-existant user");
#line 91
testRunner.Then("I receive an exception");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Account administration")]
        public virtual void AccountAdministration()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Account administration", ((string[])(null)));
#line 93
this.ScenarioSetup(scenarioInfo);
#line 95
testRunner.Given("I am a potential user");
#line 96
testRunner.When("I sign up for an account that is available");
#line 97
testRunner.Then("it is given to me");
#line 99
testRunner.Given("I am a potential user");
#line 100
testRunner.When("I sign up for an account that is not available");
#line 101
testRunner.Then("it will not allow me to have that account");
#line 103
testRunner.Given("I am an existing user");
#line 104
testRunner.And("I change my email address");
#line 105
testRunner.And("the email address is not associated with another account");
#line 106
testRunner.Then("the change is set in the system");
#line 108
testRunner.Given("I am an existing user");
#line 109
testRunner.And("I change my email address");
#line 110
testRunner.And("the email address is associated with another user");
#line 111
testRunner.Then("no change is made");
#line 112
testRunner.And("an exception is thrown");
#line 114
testRunner.Given("I am an existing user");
#line 115
testRunner.And("I change my RequiresApprovalToBeFriends");
#line 116
testRunner.Then("the change is set in the system");
#line 118
testRunner.Given("I am an existing user");
#line 119
testRunner.And("I change my profile to be visible to friends only");
#line 120
testRunner.Then("the change is set in the system");
#line 122
testRunner.Given("I am an existing user");
#line 123
testRunner.And("I change my profile to allow messages from non-friends");
#line 124
testRunner.Then("the change is set in the system");
#line 126
testRunner.Given("I am an existing user");
#line 127
testRunner.And("I change my name");
#line 128
testRunner.Then("the change is set in the system");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Group administration")]
        public virtual void GroupAdministration()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Group administration", ((string[])(null)));
#line 130
this.ScenarioSetup(scenarioInfo);
#line 132
testRunner.Given("I am an existing user");
#line 133
testRunner.And("I am a group admin");
#line 134
testRunner.When("I need a speaker for a new event");
#line 135
testRunner.Then("I can push a notification that I am looking for speakers for that event");
#line 137
testRunner.Given("I am an existing user");
#line 138
testRunner.And("I am a group admin");
#line 139
testRunner.When("I try to create a new event for the group");
#line 140
testRunner.Then("the event is added to my events I\'m attending");
#line 141
testRunner.And("the group is added to events I\'m admin");
#line 142
testRunner.And("it is added to the other group\'s admins events admin");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
